/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { InputSize, InputType, UserInputEvent } from "./components/types";
export namespace Components {
    interface CustomInput {
        "inputTitle": string;
        "isValid": boolean;
        "size": InputSize;
        "type": InputType;
        "validationPattern": string;
    }
    interface UrlInput {
        "inputTitle": string;
        "isValid": boolean;
        "size": InputSize;
        "type": InputType;
        "validationPattern": string;
    }
}
declare global {
    interface HTMLCustomInputElement extends Components.CustomInput, HTMLStencilElement {
    }
    var HTMLCustomInputElement: {
        prototype: HTMLCustomInputElement;
        new (): HTMLCustomInputElement;
    };
    interface HTMLUrlInputElement extends Components.UrlInput, HTMLStencilElement {
    }
    var HTMLUrlInputElement: {
        prototype: HTMLUrlInputElement;
        new (): HTMLUrlInputElement;
    };
    interface HTMLElementTagNameMap {
        "custom-input": HTMLCustomInputElement;
        "url-input": HTMLUrlInputElement;
    }
}
declare namespace LocalJSX {
    interface CustomInput {
        "inputTitle"?: string;
        "isValid"?: boolean;
        "onOnUserInput"?: (event: CustomEvent<UserInputEvent>) => void;
        "size"?: InputSize;
        "type"?: InputType;
        "validationPattern"?: string;
    }
    interface UrlInput {
        "inputTitle"?: string;
        "isValid"?: boolean;
        "onUserInput"?: (event: CustomEvent<UserInputEvent>) => void;
        "size"?: InputSize;
        "type"?: InputType;
        "validationPattern"?: string;
    }
    interface IntrinsicElements {
        "custom-input": CustomInput;
        "url-input": UrlInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-input": LocalJSX.CustomInput & JSXBase.HTMLAttributes<HTMLCustomInputElement>;
            "url-input": LocalJSX.UrlInput & JSXBase.HTMLAttributes<HTMLUrlInputElement>;
        }
    }
}
